# Generated by Django 6.0.6 on 2026-06-04 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Kelas ikon CSS atau emoji, misal: 🎤', max_length=50)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fasilitas',
                'verbose_name_plural': 'Fasilitas',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/')),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promosi',
                'verbose_name_plural': 'Promosi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Tipe')),
                ('capacity', models.PositiveIntegerField(verbose_name='Kapasitas (orang)')),
                ('price_per_hour', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Harga per Jam (Rp)')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='room_types/', verbose_name='Foto Ruangan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipe Ruangan',
                'verbose_name_plural': 'Tipe Ruangan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Ruangan')),
                ('room_code', models.CharField(help_text='Contoh: A01, VIP-1 (untuk denah grid)', max_length=20, unique=True, verbose_name='Kode Ruangan')),
                ('capacity', models.PositiveIntegerField(help_text='Kosongkan logika UI bisa mengikuti tipe; isi jika berbeda dari tipe.', verbose_name='Kapasitas')),
                ('price_per_hour', models.DecimalField(decimal_places=0, help_text='Bisa disamakan dengan tipe atau di-override per ruangan.', max_digits=10, verbose_name='Harga per Jam (Rp)')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Foto Ruangan')),
                ('grid_row', models.PositiveSmallIntegerField(default=0, help_text='Posisi baris pada denah admin (CSS Grid).', verbose_name='Baris Denah')),
                ('grid_col', models.PositiveSmallIntegerField(default=0, help_text='Posisi kolom pada denah admin (CSS Grid).', verbose_name='Kolom Denah')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='karaoke.roomtype', verbose_name='Tipe Ruangan')),
            ],
            options={
                'verbose_name': 'Ruangan',
                'verbose_name_plural': 'Ruangan',
                'ordering': ['room_code'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Tanggal Main')),
                ('start_time', models.TimeField(verbose_name='Jam Mulai')),
                ('end_time', models.TimeField(verbose_name='Jam Selesai')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Pembayaran'), ('LUNAS', 'Lunas / Sedang Dipakai'), ('BATAL', 'Dibatalkan')], default='PENDING', max_length=10, verbose_name='Status Pesanan')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total Harga (Rp)')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Member')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='karaoke.room', verbose_name='Ruangan')),
            ],
            options={
                'verbose_name': 'Pesanan',
                'verbose_name_plural': 'Pesanan',
                'ordering': ['-booking_date', '-start_time'],
                'indexes': [models.Index(fields=['booking_date', 'room'], name='karaoke_boo_booking_26c569_idx'), models.Index(fields=['user', 'status'], name='karaoke_boo_user_id_f4484e_idx')],
            },
        ),
    ]
