# Generated by Django 6.0.6 on 2026-06-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0002_bookingpackage_remove_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='grid_col',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='grid_row',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
