# Generated by Django 6.0.5 on 2026-06-05 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0003_grid_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Menunggu Pembayaran'), ('LUNAS', 'Lunas'), ('BATAL', 'Dibatalkan')], default='PENDING', max_length=10, verbose_name='Status Pesanan'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='karaoke.roomtype', verbose_name='Tipe Ruangan'),
        ),
    ]
